# Generated by Django 4.1.1 on 2022-12-27 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nota', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpin', models.CharField(max_length=200, unique=True)),
                ('nombre_proyecto', models.TextField()),
                ('fecha_ingreso', models.DateField()),
                ('presentacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='municipios',
            name='estado',
        ),
        migrations.AlterField(
            model_name='estados_proyectos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectores_inversion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='revisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateField()),
                ('estado_anterior', models.CharField(max_length=70)),
                ('detalle_revision', models.TextField(blank=True)),
                ('archivo_revision', models.FileField(blank=True, null=True, upload_to='static/archivos_proyectos')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_proyectos.proyectos')),
            ],
        ),
        migrations.AddField(
            model_name='proyectos',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_proyectos.estados_proyectos'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='revisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_proyectos.secretarias'),
        ),
        migrations.CreateModel(
            name='proyecto_archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=200, unique=True)),
                ('vigencia', models.IntegerField(max_length=10)),
                ('valor_proyecto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_proyectos.municipios')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_proyectos.proyectos')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_proyectos.sectores_inversion')),
            ],
        ),
    ]
