# Generated by Django 4.1.1 on 2022-11-10 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_proyecto', models.CharField(max_length=200)),
                ('nombre_proyecto', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('valor_proyecto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_proyectos.estados_proyectos')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_proyectos.municipios')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_proyectos.secretarias')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_proyectos.sectores_inversion')),
            ],
        ),
    ]
