# Generated by Django 4.1.1 on 2022-12-31 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_proyectos', '0002_notas_proyectos_remove_municipios_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='estados_proyectos',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='estados_proyectos',
            name='nombre_estado',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='revisor',
        ),
        migrations.AddField(
            model_name='estados_proyectos',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_proyectos.proyectos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estados_proyectos',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_proyectos.estados'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_proyectos.estados'),
        ),
    ]
