# Generated by Django 4.1.1 on 2022-12-31 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_proyectos', '0003_estados_remove_estados_proyectos_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='estado',
        ),
    ]
