# Generated by Django 4.1.1 on 2022-11-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_proyectos', '0004_realizar_cambios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='numero_proyecto',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
