# Generated by Django 4.1.1 on 2022-12-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_proyectos', '0007_asignar_proyectos_archivo_asignado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectores_inversion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
