# Generated by Django 4.1.1 on 2023-01-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_proyectos', '0007_alter_proyectos_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto_archivo',
            name='vigencia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='revisiones',
            name='archivo_revision',
            field=models.FileField(blank=True, null=True, upload_to='static/archivos_adjuntos/'),
        ),
    ]
