# Generated by Django 4.1.1 on 2022-12-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_proyectos', '0008_alter_sectores_inversion_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nota', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='estados_proyectos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
