# Generated by Django 4.1.1 on 2023-01-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_proyectos', '0009_alter_revisiones_archivo_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisiones',
            name='archivo_revision',
            field=models.FileField(blank=True, null=True, upload_to='aplicaciones/gestion_proyectos/static/archivos_adjuntos/'),
        ),
    ]
